### ISSUE TITLE
Interleaved data format

### ISSUE THREAD

**Issue by akatav** [drchrisch/SynapseLocator#2]
Hello
Thanks for this software.

My 2 photon image data has 2 channels, say c1 and c2 and 2 different wavelengths, say w1 and w2. 
Presynaptic imaging session has 2 image stacks: C1_w1_day-1.tif, C2_w2_day-1.tif
Post synaptic imaging session has 2 image stacks: C1_w1_day+2.tif, C2_w2_day+2.tif

I have combined the above image stacks through interleaving as mentioned in the manual like so:  Interleaved image stack of {C1_w1_day-1.tif, C2_w2_day-1.tif} AND {C1_w1_day+2.tif, C2_w2_day+2.tif}. Is this correct ?

**Comment by drchrisch** [comment]
Hello akatav, yes, your description should lead to an interleaved image stack.
