### ISSUE TITLE
Voxel size xy and z params

### ISSUE THREAD

**Issue by akatav** [drchrisch/SynapseLocator#3]
Hi
The z-slice in our dataset is 1 micron thick. Each pixel is around 0.082 microns. I gave 0.082*0.082 for "xy" and 1 for "z". 
I hope i got that right. 
However, the software seems to take a really long time to load the images. What is wrong here?
Thanks.

**Comment by drchrisch** [comment]
Hi akatav, indeed, the image pre-processing step may take a while, especially with large image stacks. What is the typical size of your image stacks?

**Comment by akatav** [comment]
Thank you for the response @drchrisch. The stack size is only 30 frames. Each image is 512*512. As my images are already preprocessed (motion corrected, registered, aligned and deconvolved), i think i can safely skip the preprocessing step. I did not do that earlier. I may only need the 'filtering and background subtraction' step perhaps. Here is a snapshot of the settings:

![git-snapshot](https://user-images.githubusercontent.com/721570/111129924-fcb38700-85b9-11eb-8ea3-a8b1ab21fd30.png)

In this case, I do not get the popup to choose xy and z values. On saving results (after running the locator), the Label and Spot summary images are blank.

**Comment by drchrisch** [comment]
Well, the images are loaded and you should be able use the default model for spot finding or you could build a new one.
